services:
  dev:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev -- --host --port 4321"
    environment:
      - NODE_ENV=development
    user: "node"

